set(CMAKE_SYSTEM_NAME none)
set(CMAKE_SYSTME_PROCESSOR none)
set(CMAKE_SYSROOT /opt/gcc-x86_64-elf)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER ${CMAKE_SYSROOT}/bin/x86_64-elf-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_SYSROOT}/bin/x86_64-elf-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)